"""Agregar columna fecha_devolucion al modelo Prestamo

Revision ID: 38451f2e4331
Revises: 6bc292c881fc
Create Date: 2025-05-07 09:34:59.782466

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38451f2e4331"
down_revision = "6bc292c881fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prestamo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fecha_devolucion", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prestamo", schema=None) as batch_op:
        batch_op.drop_column("fecha_devolucion")

    # ### end Alembic commands ###
