"""Permitir usuario_id NULL en reserva

Revision ID: e9887353a8a0
Revises: 38451f2e4331
Create Date: 2025-05-07 10:20:17.941142

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e9887353a8a0"
down_revision = "38451f2e4331"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reserva", schema=None) as batch_op:
        batch_op.alter_column(
            "libro_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )
        batch_op.alter_column(
            "usuario_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reserva", schema=None) as batch_op:
        batch_op.alter_column(
            "usuario_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.alter_column(
            "libro_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )

    # ### end Alembic commands ###
