"""Crear tablas iniciales

Revision ID: ebbd4bad22bd
Revises: 
Create Date: 2025-04-26 00:20:23.997051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbd4bad22bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libro_autor'), ['autor'], unique=False)
        batch_op.create_index(batch_op.f('ix_libro_isbn'), ['isbn'], unique=True)
        batch_op.create_index(batch_op.f('ix_libro_titulo'), ['titulo'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_Usuario__contrasena_hash', sa.String(length=60), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('token_confirmacion', sa.String(length=100), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('cuenta_bloqueada_hasta', sa.DateTime(), nullable=True),
    sa.Column('token_expiracion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamo')
    op.drop_table('usuario')
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libro_titulo'))
        batch_op.drop_index(batch_op.f('ix_libro_isbn'))
        batch_op.drop_index(batch_op.f('ix_libro_autor'))

    op.drop_table('libro')
    # ### end Alembic commands ###
